hugoblox:
  schema: "2.0"
  identity:
    type: local_business
    tagline: Connecting Networks
    logo: "logo.png"
    description: ""
  theme:
    mode: light
    pack: default
    colors:
      primary: orange
      secondary: "yellow"
      neutral: ""
    colors_light:
      primary: orange
  typography:
    font: native
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    show_logo: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © Ripple Networks {year}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
